### ISSUE TITLE
Autocompletion for commands, operations, names in memory and filenames when loading

### ISSUE THREAD

**Issue by jmansilla** [jmansilla/lamedh#6]

**Comment by akielbowicz** [comment]
[rlcompleter](https://docs.python.org/3/library/rlcompleter.html#module-rlcompleter) is a stdlib module that might help with this, works with `readline`

**Comment by akielbowicz** [comment]
Digging a bit more this looks more feature-complete https://docs.python.org/3/library/cmd.html#module-cmd
